apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sdjango-celery-beat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: celery-beat
  template:
    metadata:
      labels:
        component: celery-beat
    spec:
      containers:
        - name: celery-beat
          image: mamithi/k8sdjango:v0.0.5
          command: ['celery', '-A', 'k8s_django', 'beat', '-l', 'debug']
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: k8sdjango-postgres-credentials
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k8sdjango-postgres-credentials
                  key: password

            - name: POSTGRES_HOST
              value: k8sdjango-postgres-service

            - name: REDIS_HOST
              value: k8sdjango-redis-service