apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sdjango-celery-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: celery-worker
  template:
    metadata:
      labels:
        component: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: mamithi/k8sdjango:v0.0.5
          command: ['celery', '-A', 'k8s_django', 'worker', '-l', 'info']
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: k8sdjango-postgres-credentials
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k8sdjango-postgres-credentials
                  key: password

            - name: POSTGRES_HOST
              value: k8sdjango-postgres-service

            - name: REDIS_HOST
              value: k8sdjango-redis-service
