kind: PersistentVolume
apiVersion: v1
metadata:
  name: k8sdjango-postgres-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgres-pv