apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8sdjango-postgres-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: k8sdjango-postgres-pv